dataaccessregistry:
  readonlyconnection: "data source=NB101389\\SQLSERVER;initial catalog=Pedido;user id=santamaria;password=santamaria"
  transactionalconnection: "data source=NB101389\\SQLSERVER;initial catalog=Pedido;user id=santamaria;password=santamaria"
  providername: System.Data.SqlClient

AMQStreams:
  BootstrapServer: "SSL://cluster-kafka-bootstrap-amq-streams-test.apps.ocptest.andreani.com.ar:443"
  SchemaUrl: "http://apicurioregistry.apps.ocptest.andreani.com.ar/apis/ccompat/v6"
  Protocol: "Ssl"
  SslCertificateLocation: "./kafka.pem"
  EnableSslCertificateVerification: false
  AutoOffsetReset: "Earliest"
  AutoRegisterSchemas: true
  maxRetry: 3